<?xml version="1.0" encoding="UTF-8"?>
<testExecutions version="1">
  <file path="/mnt/d/Exercise/meetup-aws/__tests__/unit/just-lambda.test.ts">
    <testCase name="Randome number sum less then 100" duration="8"/>
  </file>
  <file path="/mnt/d/Exercise/meetup-aws/__tests__/unit/sqs-triggered-lambda.test.ts">
    <testCase name="Sum of two numbers" duration="12"/>
  </file>
  <file path="/mnt/d/Exercise/meetup-aws/__tests__/unit/with-input-lambda.test.ts">
    <testCase name="Sum of two numbers" duration="9"/>
  </file>
  <file path="/mnt/d/Exercise/meetup-aws/__tests__/unit/api-triggered-lambda.test.ts">
  </file>
  <file path="/mnt/d/Exercise/meetup-aws/__tests__/unit/s3-triggered-lambda.test.ts">
    <testCase name="Sum of two numbers" duration="11">
      <failure message="Error: expect(received).toBe(expected) // Object.is equality"><![CDATA[Error: expect(received).toBe(expected) // Object.is equality

Expected: 21
Received: 12
    at /mnt/d/Exercise/meetup-aws/__tests__/unit/s3-triggered-lambda.test.ts:6:40
    at Generator.next (<anonymous>)
    at fulfilled (/mnt/d/Exercise/meetup-aws/__tests__/unit/s3-triggered-lambda.test.ts:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)]]></failure>
    </testCase>
  </file>
</testExecutions>